# Generated by Django 3.2.16 on 2023-01-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230115_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
